osx_image: xcode9.4
language: objective-c
install:
  - gem install xcpretty-travis-formatter
  - git clone https://github.com/MacPaw/universal-detector.git ../UniversalDetector
script:
  - xcodebuild test -project XADMaster.xcodeproj -scheme XADMasterTests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`